export const COMPANY = {
  name: "Moran Plumbing Services",
  legal: "Moran Plumbing Services LLC",
  rocLicense: "#361367",
  established: "September 2025",
  address: "17230 N 32nd Pl, Phoenix, AZ 85032",
  city: "Phoenix",
  state: "AZ",
  zip: "85032",
  phone: "(480) 431-4331",
  phoneRaw: "4804314331",
  email: "moranplumbingservices@gmail.com",
  website: "www.moranplumbingservices.com",
  instagram: "@moranplumbingservices",
  instagramUrl: "https://instagram.com/moranplumbingservices",
  hours: "24/7 Emergency Service",
  googleRating: "5.0",
  googleReviews: 10,
  tagline: "No Job is Too Big or Too Small",
  description: "Family-owned Phoenix plumbing company providing residential, commercial, and new construction plumbing services with integrity and exceptional service.",
};

export const SERVICES = [
  {
    slug: "residential",
    title: "Residential Plumbing",
    shortTitle: "Residential",
    description: "Complete home plumbing services from repairs to installations. We handle everything from leaky faucets to whole-home repiping.",
    icon: "home",
    features: [
      "Drain Cleaning",
      "Water Treatment",
      "Water Heaters",
      "Leak Detection",
      "Slab Leaks",
      "Gas Lines",
      "Camera Inspections",
      "Faucet & Fixture Repair",
      "Toilet Repair & Installation",
      "Garbage Disposal Services",
    ],
  },
  {
    slug: "commercial",
    title: "Commercial & Industrial Plumbing",
    shortTitle: "Commercial",
    description: "Professional plumbing solutions for businesses, restaurants, and industrial facilities throughout the Phoenix area.",
    icon: "building",
    features: [
      "Commercial Drain Cleaning",
      "Hydro Jetting",
      "Pump Repair",
      "Gas Lines",
      "Grease Trap Repair",
      "Camera Inspections",
      "Backflow Installation & Testing",
      "Water Line Services",
      "Preventive Maintenance",
    ],
  },
  {
    slug: "new-construction",
    title: "New Construction Plumbing",
    shortTitle: "New Construction",
    description: "Expert plumbing installation for new builds, custom homes, apartments, and commercial buildings.",
    icon: "hardhat",
    features: [
      "Custom Home Builds",
      "Apartment Complexes",
      "Commercial Buildings",
      "Industrial Facilities",
      "Rough-In Plumbing",
      "Finish Plumbing",
      "Plan Review & Consultation",
      "Code Compliance",
    ],
  },
  {
    slug: "water-heaters",
    title: "Water Heater & Boiler Services",
    shortTitle: "Water Heaters",
    description: "Installation, repair, and maintenance for all types of water heaters including tankless systems.",
    icon: "flame",
    features: [
      "Residential Installation",
      "Commercial Installation",
      "Diagnostic & Repair",
      "Hydronic Systems",
      "Tankless Water Heaters",
      "Traditional Tank Heaters",
      "Boiler Systems",
      "Energy-Efficient Upgrades",
    ],
  },
  {
    slug: "drain-cleaning",
    title: "Drain Cleaning Services",
    shortTitle: "Drain Cleaning",
    description: "Professional drain cleaning and clearing services to keep your plumbing flowing smoothly.",
    icon: "droplet",
    features: [
      "Clogged Drain Repair",
      "Hydro Jetting",
      "Sewer Line Cleaning",
      "Kitchen Drain Cleaning",
      "Bathroom Drain Service",
      "Floor Drain Maintenance",
      "Video Camera Inspection",
      "Root Removal",
    ],
  },
  {
    slug: "leak-detection",
    title: "Leak Detection & Slab Leaks",
    shortTitle: "Leak Detection",
    description: "Advanced leak detection services to find and repair hidden leaks before they cause major damage.",
    icon: "search",
    features: [
      "Electronic Leak Detection",
      "Slab Leak Repair",
      "Underground Leak Location",
      "Water Line Leak Repair",
      "Pool Leak Detection",
      "Thermal Imaging",
      "Non-Invasive Detection",
      "Emergency Leak Services",
    ],
  },
  {
    slug: "gas-lines",
    title: "Gas Line Services",
    shortTitle: "Gas Lines",
    description: "Safe and professional gas line installation, repair, and inspection services.",
    icon: "zap",
    features: [
      "Gas Line Installation",
      "Gas Line Repair",
      "Gas Leak Detection",
      "Appliance Hookups",
      "Gas Line Inspection",
      "Natural Gas Services",
      "Propane Line Services",
      "Safety Inspections",
    ],
  },
];

export const LOCATIONS = [
  {
    slug: "phoenix",
    city: "Phoenix",
    state: "AZ",
    description: "Proudly serving Phoenix with 24/7 emergency plumbing services. Our headquarters in North Phoenix means fast response times throughout the Valley.",
    isPrimary: true,
    neighborhoods: ["North Phoenix", "Central Phoenix", "South Phoenix", "Arcadia", "Paradise Valley", "Ahwatukee"],
  },
  {
    slug: "glendale",
    city: "Glendale",
    state: "AZ",
    description: "Reliable plumbing services for Glendale homes and businesses. From Downtown Glendale to Arrowhead, we're your trusted local plumber.",
    isPrimary: true,
    neighborhoods: ["Downtown Glendale", "Arrowhead", "Westgate", "Historic District"],
  },
  {
    slug: "mesa",
    city: "Mesa",
    state: "AZ",
    description: "Expert plumbing solutions for Mesa residents. We serve all Mesa neighborhoods with quality workmanship and honest pricing.",
    isPrimary: true,
    neighborhoods: ["Downtown Mesa", "East Mesa", "Red Mountain", "Superstition Springs", "Falcon Field"],
  },
  {
    slug: "tempe",
    city: "Tempe",
    state: "AZ",
    description: "Professional plumbing services for Tempe homes, businesses, and ASU-area properties. Fast, reliable, and affordable.",
    isPrimary: true,
    neighborhoods: ["Downtown Tempe", "Mill Avenue", "ASU Area", "South Tempe", "Tempe Marketplace"],
  },
  {
    slug: "cave-creek",
    city: "Cave Creek",
    state: "AZ",
    description: "Serving Cave Creek and Carefree with specialized plumbing services. We understand the unique needs of desert properties.",
    isPrimary: true,
    neighborhoods: ["Cave Creek", "Carefree", "Black Mountain", "Desert Hills"],
  },
  {
    slug: "flagstaff",
    city: "Flagstaff",
    state: "AZ",
    description: "Expanding our quality plumbing services to Northern Arizona. Flagstaff residents can count on Moran Plumbing for all their needs.",
    isPrimary: true,
    neighborhoods: ["Downtown Flagstaff", "NAU Area", "Flagstaff Ranch", "Kachina Village"],
  },
];

export const TESTIMONIALS = [
  {
    name: "Sarah M.",
    location: "Phoenix, AZ",
    rating: 5,
    text: "Moran Plumbing saved us during a midnight emergency. They arrived within an hour and fixed our burst pipe quickly. True professionals!",
  },
  {
    name: "Robert J.",
    location: "Glendale, AZ",
    rating: 5,
    text: "Honest pricing and quality work. They installed our new tankless water heater and explained everything clearly. Highly recommend!",
  },
  {
    name: "Michelle T.",
    location: "Mesa, AZ",
    rating: 5,
    text: "Finally found a plumber I can trust! The team was professional, clean, and fixed our slab leak without destroying our floors.",
  },
  {
    name: "David K.",
    location: "Tempe, AZ",
    rating: 5,
    text: "Used them for our restaurant's plumbing needs. Fast response, fair pricing, and they understand commercial requirements.",
  },
];

export const BLOG_POSTS = [
  {
    slug: "hard-water-problems-arizona",
    title: "Hard Water Problems in Arizona: What Every Homeowner Should Know",
    excerpt: "Arizona's hard water can wreak havoc on your plumbing. Learn how to identify and address hard water issues in your Phoenix-area home.",
    date: "2026-02-01",
    category: "Water Quality",
    readTime: "5 min read",
  },
  {
    slug: "water-heater-maintenance-tips",
    title: "Water Heater Maintenance Tips for Phoenix Homeowners",
    excerpt: "Extend the life of your water heater with these essential maintenance tips designed for Arizona's unique climate.",
    date: "2026-01-28",
    category: "Maintenance",
    readTime: "4 min read",
  },
  {
    slug: "signs-you-need-slab-leak-repair",
    title: "5 Warning Signs You Need Slab Leak Repair",
    excerpt: "Slab leaks can cause serious damage if left untreated. Here's how to spot the early warning signs before it's too late.",
    date: "2026-01-20",
    category: "Repairs",
    readTime: "6 min read",
  },
  {
    slug: "commercial-plumbing-maintenance-checklist",
    title: "Commercial Plumbing Maintenance Checklist for Phoenix Businesses",
    excerpt: "Keep your business running smoothly with this comprehensive plumbing maintenance checklist.",
    date: "2026-01-15",
    category: "Commercial",
    readTime: "7 min read",
  },
  {
    slug: "tankless-vs-tank-water-heaters",
    title: "Tankless vs Tank Water Heaters: Which is Right for Arizona?",
    excerpt: "Comparing tankless and traditional water heaters for Arizona homes. Costs, benefits, and what works best in our climate.",
    date: "2026-01-10",
    category: "Water Heaters",
    readTime: "5 min read",
  },
  {
    slug: "emergency-plumbing-tips",
    title: "Emergency Plumbing Tips: What to Do Before the Plumber Arrives",
    excerpt: "Quick actions that can minimize damage during a plumbing emergency. Essential knowledge for every homeowner.",
    date: "2026-01-05",
    category: "Emergency",
    readTime: "4 min read",
  },
  {
    slug: "new-construction-plumbing-timeline",
    title: "New Construction Plumbing Timeline: What to Expect",
    excerpt: "Building a new home in Phoenix? Here's what you need to know about the plumbing installation process.",
    date: "2025-12-28",
    category: "New Construction",
    readTime: "6 min read",
  },
  {
    slug: "seasonal-plumbing-tips-arizona",
    title: "Seasonal Plumbing Tips for Arizona Homes",
    excerpt: "From monsoon prep to winter protection, keep your plumbing running smoothly year-round in the Arizona climate.",
    date: "2025-12-20",
    category: "Maintenance",
    readTime: "5 min read",
  },
  {
    slug: "how-to-choose-plumber-phoenix",
    title: "How to Choose a Plumber in Phoenix: A Complete Guide",
    excerpt: "What to look for when hiring a plumber. Red flags, questions to ask, and how to verify credentials.",
    date: "2025-12-15",
    category: "Tips",
    readTime: "6 min read",
  },
  {
    slug: "drain-cleaning-diy-vs-professional",
    title: "Drain Cleaning: DIY vs Professional Service",
    excerpt: "When can you handle a clogged drain yourself, and when should you call a professional? We break it down.",
    date: "2025-12-10",
    category: "Drain Cleaning",
    readTime: "5 min read",
  },
];

export const NAV_ITEMS = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  {
    label: "Services",
    href: "/services",
    children: SERVICES.map((s) => ({ label: s.shortTitle, href: `/services/${s.slug}` })),
  },
  {
    label: "Service Areas",
    href: "/locations",
    children: LOCATIONS.map((l) => ({ label: l.city, href: `/locations/${l.slug}` })),
  },
  { label: "Blog", href: "/blog" },
  { label: "Contact", href: "/contact" },
];
